# Site settings
title: Music Code Me
description: 张斌的博客
keywords: Code, Music, Blogging, Fun
author: 张斌
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://musiccode.me" # the base hostname & protocol for your site
permalink: none
